MESSAGES_PAGE_SIZE = 50

CHAT_ALREADY_EXISTS = 'CHAT_ALREADY_EXISTS';
CHAT_NEW = 'CHAT_NEW'

SEND_MESSAGE = 'SEND_MESSAGE'
READ_MESSAGE = 'READ_MESSAGE'
IS_USER_TYPING = 'IS_USER_TYPING'
DISPLAY_CHAT_ON_RECIPIENT_SIDE = 'DISPLAY_CHAT_ON_RECIPIENT_SIDE'
